name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Update to the latest version
        with:
          python-version: '3.8'  # Specify the version of Python you want to use
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run the EPG merger
        run: |
          python merge_epg.py
