name: CI

on:
  push:
    branches:
      - main  # Adjust according to your branch names if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated version
        
      - name: Set up Python
        uses: actions/setup-python@v4  # Updated version
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run the EPG merger
        run: |
          python merge_epg.py
