name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify the version you need
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install the dependencies listed in requirements.txt
          
      - name: Run the EPG merger
        run: |
          python merge_epg.py  # Run the Python script
